//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dek.Bel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman, 12pt")]
        public global::System.Drawing.Font CitationFont {
            get {
                return ((global::System.Drawing.Font)(this["CitationFont"]));
            }
            set {
                this["CitationFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[…]")]
        public string DeselectionMarker {
            get {
                return ((string)(this["DeselectionMarker"]));
            }
            set {
                this["DeselectionMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StorageFolder {
            get {
                return ((string)(this["StorageFolder"]));
            }
            set {
                this["StorageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnderlineEmphasis {
            get {
                return ((bool)(this["UnderlineEmphasis"]));
            }
            set {
                this["UnderlineEmphasis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BoldEmphasis {
            get {
                return ((bool)(this["BoldEmphasis"]));
            }
            set {
                this["BoldEmphasis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color PdfUnderlineColor {
            get {
                return ((global::System.Drawing.Color)(this["PdfUnderlineColor"]));
            }
            set {
                this["PdfUnderlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 255")]
        public global::System.Drawing.Color PdfHighLightColor {
            get {
                return ((global::System.Drawing.Color)(this["PdfHighLightColor"]));
            }
            set {
                this["PdfHighLightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDebugMessages {
            get {
                return ((bool)(this["ShowDebugMessages"]));
            }
            set {
                this["ShowDebugMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoWritePdfOnClose {
            get {
                return ((bool)(this["AutoWritePdfOnClose"]));
            }
            set {
                this["AutoWritePdfOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 255")]
        public global::System.Drawing.Color PdfMarginBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["PdfMarginBoxColor"]));
            }
            set {
                this["PdfMarginBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public int PdfMarginBoxWidth {
            get {
                return ((int)(this["PdfMarginBoxWidth"]));
            }
            set {
                this["PdfMarginBoxWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int PdfMarginBoxHeight {
            get {
                return ((int)(this["PdfMarginBoxHeight"]));
            }
            set {
                this["PdfMarginBoxHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PdfmarginBoxBorder {
            get {
                return ((float)(this["PdfmarginBoxBorder"]));
            }
            set {
                this["PdfmarginBoxBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int PdfMarginBoxMargin {
            get {
                return ((int)(this["PdfMarginBoxMargin"]));
            }
            set {
                this["PdfMarginBoxMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string PdfMarginBoxVisualMode {
            get {
                return ((string)(this["PdfMarginBoxVisualMode"]));
            }
            set {
                this["PdfMarginBoxVisualMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PdfMarginBoxRightMargin {
            get {
                return ((bool)(this["PdfMarginBoxRightMargin"]));
            }
            set {
                this["PdfMarginBoxRightMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times-Roman")]
        public string PdfMarginBoxFont {
            get {
                return ((string)(this["PdfMarginBoxFont"]));
            }
            set {
                this["PdfMarginBoxFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public float PdfMarginBoxFontSize {
            get {
                return ((float)(this["PdfMarginBoxFontSize"]));
            }
            set {
                this["PdfMarginBoxFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedDatabaseFile {
            get {
                return ((string)(this["LastSelectedDatabaseFile"]));
            }
            set {
                this["LastSelectedDatabaseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reports")]
        public string ReportsFolder {
            get {
                return ((string)(this["ReportsFolder"]));
            }
            set {
                this["ReportsFolder"] = value;
            }
        }
    }
}
